const api = window.TRACESIGNAL_CONFIG?.apiUrl || '';
const app = document.querySelector('#app');
const state = { cases: [], requests: [] };
const json = async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body; };
const get = (path) => fetch(`${api}${path}`).then(json);
const post = (path, body = {}) => fetch(`${api}${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }).then(json);

app.innerHTML = `<div class="shell"><header class="top"><div><div class="brand">Trace<span>Signal</span></div><div class="subbrand">Cross-chain investigation workspace</div></div><div class="pill">DEMO MODE · FIXTURES ONLY</div></header><nav class="nav"><button data-view="dashboard" class="active">Dashboard</button><button data-view="cases">Cases</button><button data-view="validation">Validation</button><button data-view="audit">Audit log</button><button data-view="sahyog">SAHYOG</button></nav><main id="view"></main><footer>Candidate attribution, not proof of ownership. AI suggests · Evidence decides · Human confirms.</footer></div>`;
function shell(title, subtitle, content) { return `<section class="page-head"><div><div class="eyebrow">Investigation workspace</div><h1>${title}</h1><p class="muted">${subtitle}</p></div></section>${content}`; }
function statusBadge(status) { return `<span class="status status-${String(status).toLowerCase().replaceAll('_','-')}">${status}</span>`; }
function renderDashboard() { const traced = state.cases.filter((item) => item.status !== 'New').length; document.querySelector('#view').innerHTML = shell('Evidence-led tracing', 'Trace wallets forward, separate path evidence from identity evidence, and record a human decision.', `<div class="stats"><div class="card"><span class="label">Total cases</span><strong>${state.cases.length}</strong></div><div class="card"><span class="label">Traced</span><strong>${traced}</strong></div><div class="card"><span class="label">SAHYOG requests</span><strong>${state.requests.length}</strong></div><div class="card"><span class="label">Mode</span><strong>Demo</strong></div></div><div class="two-col"><div class="card"><h2>Start an investigation</h2><form id="intake"><label>Case reference<input name="case_ref" required placeholder="CASE-2026-001"></label><label>Chain<select name="chain"><option>Ethereum</option><option>Tron</option><option>Bitcoin</option></select></label><label>Wallet address<input name="wallet_address" required placeholder="0x… or wallet address"></label><label>Notes<textarea name="notes" placeholder="Internal investigator notes"></textarea></label><button class="btn">Create case</button><button type="button" class="btn secondary" id="simulate">Simulate SAHYOG intake</button></form></div><div class="card"><h2>Demo fixtures</h2><p class="muted">Deterministic traces work without external chain APIs.</p><div id="fixtures" class="fixture-list">Loading…</div></div></div><div class="card"><h2>Recent cases</h2><div id="recent"></div></div>`); document.querySelector('#intake').onsubmit = createCase; document.querySelector('#simulate').onclick = () => intake({ case_ref: 'SAHYOG-DEMO-001', chain: 'Ethereum', wallet_address: '0x1111111111111111111111111111111111111111', notes: 'Simulated incoming case' }, true); loadFixtures(); renderRecent(); }
function renderRecent() { const el = document.querySelector('#recent'); if (!el) return; el.innerHTML = state.cases.length ? `<table><tr><th>Reference</th><th>Chain</th><th>Status</th><th></th></tr>${state.cases.slice(0,8).map((item) => `<tr><td>${item.case_ref || 'Unreferenced'}</td><td>${item.chain}</td><td>${statusBadge(item.status)}</td><td><button class="link" data-case="${item.id}">Open</button></td></tr>`).join('')}</table>` : '<p class="muted">No cases yet.</p>'; el.querySelectorAll('[data-case]').forEach((button) => button.onclick = () => openCase(button.dataset.case)); }
function renderCases() { document.querySelector('#view').innerHTML = shell('Cases', 'Review all investigations and reopen any trace.', `<div class="card"><table><tr><th>Reference</th><th>Chain</th><th>Wallet</th><th>Status</th><th>Action</th></tr>${state.cases.map((item) => `<tr><td>${item.case_ref || 'Unreferenced'}</td><td>${item.chain}</td><td><small>${item.wallet_address}</small></td><td>${statusBadge(item.status)}</td><td><button class="btn small" data-case="${item.id}">Open case</button></td></tr>`).join('') || '<tr><td colspan="5" class="muted">No cases yet.</td></tr>'}</table></div>`); document.querySelectorAll('[data-case]').forEach((button) => button.onclick = () => openCase(button.dataset.case)); }
async function loadFixtures() { try { const fixtures = await get('/api/demo/fixtures'); const el = document.querySelector('#fixtures'); if (!el) return; el.innerHTML = fixtures.map((fixture) => `<div class="fixture-row"><div><strong>${fixture.name}</strong><small>${fixture.chain} · ${fixture.path.length - 1} hops · risk ${fixture.risk}/100</small></div><button class="btn small" data-fixture="${fixture.id}">Run</button></div>`).join(''); el.querySelectorAll('[data-fixture]').forEach((button) => button.onclick = () => intake({ case_ref: `DEMO-${button.dataset.fixture.toUpperCase()}`, chain: 'Demo', wallet_address: 'fixture-wallet' }, false, button.dataset.fixture)); } catch (error) { document.querySelector('#fixtures').textContent = error.message; } }
async function intake(data, sahyog = false, fixture = 'high') { try { const item = await post(sahyog ? '/api/sahyog/intake' : '/api/cases', data); state.cases.unshift(item); await openCase(item.id, fixture); } catch (error) { alert(error.message); } }
async function createCase(event) { event.preventDefault(); await intake(Object.fromEntries(new FormData(event.target).entries())); }
async function openCase(caseId, fixture = 'high') { try { const item = state.cases.find((entry) => entry.id === caseId) || await get(`/api/cases/${caseId}`); const trace = await post(`/api/cases/${caseId}/trace`, { fixture }); document.querySelector('#view').innerHTML = shell(item.case_ref || 'Case detail', `${item.chain} · ${item.wallet_address}`, renderTrace(trace)); bindTrace(item, trace); } catch (error) { alert(error.message); } }
function renderTrace(trace) { const path = trace.graph.nodes.map((node, index) => `<span class="node"><span class="badge">H${node.hop}</span>${node.address.slice(0,14)}…</span>${index < trace.graph.nodes.length - 1 ? '<span class="line"></span>' : ''}`).join(''); const evidence = (category) => trace.evidence.filter((entry) => entry.category === category).map((entry) => `<li><strong>${entry.subtype}</strong><small>${entry.source_id} · ${entry.created_at}</small></li>`).join('') || '<li class="muted">None</li>'; const candidate = trace.candidates[0]; return `<div class="alert ${trace.decision.confidence === 'NONE' ? 'danger' : ''}">${trace.decision.label} · ${trace.decision.reason.replaceAll('_',' ')} · risk ${trace.summary.risk_score}/100</div><div class="card"><div class="detail-head"><div><h2>Fund movement graph</h2><div class="path">${path}</div></div><div class="risk"><span>Risk</span><strong>${trace.summary.risk_score}</strong><small>/ 100</small></div></div><div class="actions"><button class="btn" id="rerun">Re-run snapshot</button><button class="btn secondary" id="report">Export JSON report</button></div></div><div class="two-col"><div class="card"><h2>Path evidence</h2><ul class="evidence">${evidence('PATH')}</ul></div><div class="card"><h2>Identity evidence</h2><ul class="evidence">${evidence('IDENTITY')}</ul></div></div><div class="card"><h2>Candidate VASP</h2>${candidate ? `<table><tr><th>Candidate</th><th>Confidence</th><th>Hops</th><th>Sources</th><th>Review</th></tr><tr><td>${candidate.vasp_name}<small>${candidate.address}</small></td><td>${statusBadge(candidate.confidence)}</td><td>${candidate.hops}</td><td>${candidate.evidence_count}</td><td><button class="btn small" id="confirm">Confirm</button><button class="btn small danger-btn" id="reject">Reject</button></td></tr></table>` : `<div class="empty"><strong>No Reliable VASP Found</strong><p>Checked ${trace.summary.checked.hops} hops, ${trace.summary.checked.addresses.length} addresses, and ${trace.summary.checked.sources.join(', ')}.</p></div>`}</div>`; }
function bindTrace(item, trace) { document.querySelector('#rerun').onclick = async () => { await post(`/api/traces/${trace.id}/rerun`, { mode: 'snapshot' }); openCase(item.id, trace.fixture); }; document.querySelector('#report').onclick = async () => { const report = await get(`/api/traces/${trace.id}/report?format=json`); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' })); link.download = `trace-${trace.id}.json`; link.click(); }; if (!trace.candidates[0]) return; document.querySelector('#confirm').onclick = () => review(item, trace, 'CONFIRMED'); document.querySelector('#reject').onclick = () => { const note = prompt('Why is this candidate rejected?'); if (note !== null) review(item, trace, 'REJECTED', note); }; }
async function review(item, trace, decision, note = '') { try { const reviewResult = await post(`/api/traces/${trace.id}/candidates/${trace.candidates[0].id}/review`, { decision, note }); if (decision === 'CONFIRMED') { const request = await post(`/api/cases/${item.id}/sahyog-request`, { trace_id: trace.id, candidate_id: trace.candidates[0].id }); alert(`Candidate confirmed and routed to SAHYOG: ${request.status}`); } else alert(`Candidate rejected: ${reviewResult.note}`); await refresh(); openCase(item.id, trace.fixture); } catch (error) { alert(error.message); } }
async function renderValidation() { document.querySelector('#view').innerHTML = shell('Validation', 'Run the held-out fixture set and inspect recovery and false positives.', `<div class="card"><button class="btn" id="run-validation">Run validation</button><div id="validation-result" class="validation-result"><p class="muted">No validation run yet.</p></div></div>`); document.querySelector('#run-validation').onclick = async () => { const result = await post('/api/admin/validation/run'); document.querySelector('#validation-result').innerHTML = `<div class="stats"><div><span class="label">Recovery rate</span><strong>${Math.round(result.recovery_rate * 100)}%</strong></div><div><span class="label">False positives</span><strong>${result.false_positives}</strong></div><div><span class="label">Recovered</span><strong>${result.recovered}/${result.total}</strong></div></div><table><tr><th>Fixture</th><th>Recovered</th><th>Confidence</th></tr>${result.results.map((row) => `<tr><td>${row.fixture}</td><td>${row.recovered ? 'Yes' : 'No'}</td><td>${statusBadge(row.confidence)}</td></tr>`).join('')}</table>`; }; }
async function renderAudit() { const entries = await get('/api/audit'); document.querySelector('#view').innerHTML = shell('Audit log', 'Every trace, review, rerun, routing action, and validation run is timestamped.', `<div class="card"><table><tr><th>Time</th><th>Action</th><th>Entity</th><th>Details</th></tr>${entries.slice().reverse().map((entry) => `<tr><td>${entry.ts}</td><td>${entry.action}</td><td>${entry.entity}</td><td>${entry.details ? JSON.stringify(entry.details) : ''}</td></tr>`).join('')}</table></div>`); }
async function renderSahyog() { const requests = await get('/api/sahyog/requests'); state.requests = requests; document.querySelector('#view').innerHTML = shell('SAHYOG requests', 'Mock routing status demonstrates the closed-loop workflow.', `<div class="card"><table><tr><th>Request</th><th>Case</th><th>Status</th><th>Action</th></tr>${requests.map((request) => `<tr><td>${request.id.slice(0,8)}…</td><td>${request.case_id.slice(0,8)}…</td><td>${statusBadge(request.status)}</td><td>${request.status !== 'ACTION_TAKEN' ? `<button class="btn small" data-advance="${request.id}">Simulate response</button>` : 'Complete'}</td></tr>`).join('') || '<tr><td colspan="4" class="muted">No requests yet.</td></tr>'}</table></div>`); document.querySelectorAll('[data-advance]').forEach((button) => button.onclick = async () => { await post(`/api/sahyog/requests/${button.dataset.advance}/simulate`); renderSahyog(); }); }
async function refresh() { state.cases = await get('/api/cases'); state.requests = await get('/api/sahyog/requests'); }
async function show(view) { document.querySelectorAll('.nav button').forEach((button) => button.classList.toggle('active', button.dataset.view === view)); await refresh(); if (view === 'dashboard') renderDashboard(); else if (view === 'cases') renderCases(); else if (view === 'validation') await renderValidation(); else if (view === 'audit') await renderAudit(); else await renderSahyog(); }
document.querySelectorAll('.nav button').forEach((button) => button.onclick = () => show(button.dataset.view));
show('dashboard').catch((error) => { document.querySelector('#view').innerHTML = `<div class="card"><h2>Unable to connect</h2><p class="muted">${error.message}. Start the API with <code>npm start</code>.</p></div>`; });
